AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/dummy/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/TrailingBlankLines:
  Exclude:
    - "Gemfile"

Lint/Debugger:
  Exclude:
    - "spec/support/capybara.rb"

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'app/admin/**/*'
    - 'app/**/*_decorator.rb'
    - 'lib/tasks/*.rake'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
